// Regenerates src/data/tw-food.ts from the 衛福部食藥署「食品營養成分資料庫」(TFND)
// open dataset (data.gov.tw #8543, Open Government Data License v1.0).
//
// The raw dump is long-format (~226k rows, one per nutrient). We pivot it to one
// row per food keeping only 每100克 protein (粗蛋白) + calories (熱量), which is
// all the app grounds against. Output is a tab/newline-encoded string constant so
// the TypeScript checker stays fast and the runtime parse is trivial.
//
// Usage:
//   node scripts/build-food-db.mjs            # download fresh from FDA
//   node scripts/build-food-db.mjs some.json  # pivot an already-extracted JSON
//
// The dataset updates irregularly; this is a manual maintenance step, not part of
// CI. Commit the regenerated src/data/tw-food.ts.

import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const ZIP_URL =
  "https://data.fda.gov.tw/opendata/exportDataList.do?method=ExportData&InfoId=20&logType=5";
const OUT = fileURLToPath(new URL("../src/data/tw-food.ts", import.meta.url));

// 每100克 analysis items we keep, mapped to output field.
const WANT = { 熱量: "kcal", 粗蛋白: "protein" };

function loadRows(localPath) {
  if (localPath) {
    console.log(`reading ${localPath}`);
    return JSON.parse(readFileSync(localPath, "utf8"));
  }
  const dir = mkdtempSync(join(tmpdir(), "tfnd-"));
  try {
    const zip = join(dir, "tfnd.zip");
    console.log(`downloading ${ZIP_URL}`);
    execFileSync("curl", ["-sL", ZIP_URL, "-o", zip]);
    console.log("unzipping…");
    execFileSync("unzip", ["-o", zip, "-d", dir], { stdio: "ignore" });
    // the archive contains a single 20_5.json
    const name = execFileSync("sh", ["-c", `ls ${dir}/*.json`]).toString().trim().split("\n")[0];
    return JSON.parse(readFileSync(name, "utf8"));
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

const rows = loadRows(process.argv[2]);
console.log(`${rows.length} raw rows`);

/** @type {Map<string, {name:string, alias:string, protein?:number, kcal?:number}>} */
const foods = new Map();
for (const r of rows) {
  const id = r["整合編號"];
  if (!id) continue;
  let f = foods.get(id);
  if (!f) {
    // aliases: 俗名 is comma/、-separated; normalize separators, drop blanks
    const alias = (r["俗名"] || "")
      .split(/[,，、;；]/)
      .map((s) => s.trim())
      .filter(Boolean)
      .join(",");
    f = { name: (r["樣品名稱"] || "").trim(), alias };
    foods.set(id, f);
  }
  const field = WANT[r["分析項"]];
  if (field) {
    const v = parseFloat(r["每100克含量"]);
    if (Number.isFinite(v)) f[field] = Math.round(v * 10) / 10;
  }
}

// keep only foods with both protein + kcal, and a name
const kept = [...foods.values()].filter(
  (f) => f.name && f.protein != null && f.kcal != null
);

// Collapse to base-name groups. The raw DB carries many near-duplicate sampling /
// cooking variants (全脂鮮乳(10月取樣), 北蕉(11月取樣), 鯖魚(烤,150度,10分)…) that add
// matching noise and ambiguity. We strip the trailing (…) qualifier and aggregate
// each base with the MEDIAN protein/kcal — a stable representative value for a
// per-100g estimate, which the AI then scales by portion.
const stripQualifier = (s) => s.replace(/\s*[（(].*$/, "").trim();
const median = (xs) => {
  const s = [...xs].sort((a, b) => a - b);
  const m = s.length >> 1;
  return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2;
};

/** @type {Map<string, {aliases:Set<string>, protein:number[], kcal:number[]}>} */
const groups = new Map();
for (const f of kept) {
  const base = stripQualifier(f.name) || f.name;
  let g = groups.get(base);
  if (!g) groups.set(base, (g = { aliases: new Set(), protein: [], kcal: [] }));
  for (const a of f.alias.split(",")) if (a) g.aliases.add(stripQualifier(a) || a);
  g.protein.push(f.protein);
  g.kcal.push(f.kcal);
}

const lines = [];
for (const [base, g] of groups) {
  g.aliases.delete(base); // an alias equal to the name is redundant
  const alias = [...g.aliases].join(",");
  const protein = Math.round(median(g.protein) * 10) / 10;
  const kcal = Math.round(median(g.kcal));
  lines.push(`${base}\t${alias}\t${protein}\t${kcal}`);
}
lines.sort((a, b) => a.localeCompare(b, "zh-Hant"));
console.log(`${kept.length} variants → ${lines.length} foods after base-name collapse`);

const banner = `// AUTO-GENERATED by scripts/build-food-db.mjs — do not edit by hand.
// Source: 衛生福利部食品藥物管理署「食品營養成分資料庫」(TFND), data.gov.tw dataset
// #8543, Open Government Data License v1.0. Per-100g 粗蛋白 (protein_g) + 熱量 (kcal).
// Near-duplicate sampling/cooking variants collapsed by base name (median per-100g).
// Encoded as name\\talias(comma-sep)\\tprotein\\tkcal per line. ${lines.length} foods.\n`;
const body = `export const TW_FOOD_RAW = \`\n${lines.join("\n").replace(/`/g, "\\`")}\n\`;\n`;
writeFileSync(OUT, banner + body);
console.log(`wrote ${OUT}`);
